let fs = require('fs');
let ruSynodal = require('./assets/ru_synodal.json');

const names = {
  "Бытие": "Бытие",
  "Исход": "Исход",
  "Левит": "Левит",
  "Числа": "Числа",
  "Deuteronomy": "Второзаконие",
  "Joshua": "Иисус Навин",
  "Judges": "Судьи",
  "Ruth": "Руфь",
  "Ruth": "Руфь",
  "1 Samuel": "1 Царств",
  "2 Samuel": "2 Царств",
  "1 Kings": "3 Царств",
  "2 Kings": "4 Царств",
  "1 Chronicles": "1 Паралипоменон",
  "2 Chronicles": "2 Паралипоменон",
  "Ezra": "Ездра",
  "Nehemiah": "Неемия",
  "Esther": "Есфирь",
  "Job": "Иов",
  "Psalms": "Псалтирь",
  "Proverbs": "Притчи",
  "Ecclesiastes": "Екклесиаст",
  "Song of Solomon": "Песня Песней",
  "Isaiah": "Исаия",
  "Jeremiah": "Иеремия",
  "Lamentations": "Плач Иеремии",
  "Ezekiel": "Иезекииль",
  "Daniel": "Даниил",
  "Hosea": "Осия",
  "Joel": "Иоиль",
  "Amos": "Амос",
  "Obadiah": "Авдий",
  "Jonah": "Иона",
  "Micah": "Михей",
  "Nahum": "Наум",
  "Habakkuk": "Аввакум",
  "Zephaniah": "Софония",
  "Haggai": "Аггей",
  "Zechariah": "Захария",
  "Malachi": "Малахия",
  "Matthew": "От Матфея",
  "Mark": "От Марка",
  "Luke": "От Луки",
  "John": "От Иоанна",
  "Acts": "Деяния",
  "Romans": "Римлянам",
  "1 Corinthians": "1 Коринфянам",
  "2 Corinthians": "2 Коринфянам",
  "Galatians": "Галатам",
  "Ephesians": "Ефесянам",
  "Philippians": "Филлипийцам",
  "Colossians": "Колоссянам",
  "1 Thessalonians": "1 Фессалоникийцам",
  "2 Thessalonians": "2 Фессалоникийцам",
  "1 Timothy": "1 Тимофею",
  "2 Timothy": "2 Тимофею",
  "Titus": "Титу",
  "Philemon": "Филимону",
  "Hebrews": "Евреям",
  "James": "Иакова",
  "1 Peter": "1 Петра",
  "2 Peter": "2 Петра",
  "1 John": "1 Иоанна",
  "2 John": "2 Иоанна",
  "3 John": "3 Иоанна",
  "Jude": "Иуды",
  "Revelation": "Откровение",
};

ruSynodal.forEach(book => {
  book.name = names[book.name];
});

fs.writeFile('./assets/ru_synodal_updated.json', JSON.stringify(ruSynodal), (err) => {
  if(err) throw new err;
});
